import { MenuItem, DailySpecial } from './types';

export const menuItems: MenuItem[] = [
  {
    id: '1',
    name: 'Idli',
    description: 'Soft steamed rice cakes served with sambar and coconut chutney',
    price: 12,
    image: '/images/idly.png',
    category: 'breakfast',
    available: true,
  },
  {
    id: '2',
    name: 'Pongle',
    description: 'fermented crepe filled with spiced potato filling',
    price: 60,
    image: '/images/polgle.png',
    category: 'breakfast',
    available: true,
    isSpecial: true,
  },
  {
    id: '3',
    name: 'kal dosai',
    description: 'Crispy fermented crepe served with sambar and chutneys',
    price: 30,
    image: '/images/kal dosai.png',
    category: 'breakfast',
    available: true,
  },
  {
    id: '4',
    name: 'special dosai',
    description: 'Crispy pastry filled with spiced potatoes and peas',
    price: 50,
    image: '/images/special dosai.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '5',
    name: 'Vadai',
    description: 'Spiced potato fritter in a soft bun with chutneys',
    price: 12,
    image: '/images/vadai.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '6',
    name: 'poori set',
    description: 'Traditional Indian spiced tea with milk',
    price: 30,
    image: '/images/poori set.png',
    category: 'beverages',
    available: true,
  },
  {
    id: '7',
    name: 'poori',
    description: 'Authentic South Indian filter coffee',
    price: 12,
    image: '/images/poori.png',
    category: 'beverages',
    available: true,
  },
  {
    id: '8',
    name: 'parotta',
    description: 'Refreshing iced coffee with milk and sugar',
    price: 12,
    image: '/images/parotta.png',
    category: 'beverages',
    available: true,
  },
  {
    id: '9',
    name: 'wheat parotta',
    description: 'Complete meal with dal, sabzi, roti, rice, and salad',
    price: 25,
    image: '/images/wheat parotta.png',
    category: 'meals',
    available: true,
    isSpecial: true,
  },
  {
    id: '10',
    name: 'veechu parotta',
    description: 'Spiced chickpea curry with fluffy fried bread',
    price: 25,
    image: '/images/veechu parotta.png',
    category: 'meals',
    available: true,
  },
  {
    id: '11',
    name: 'egg veechu parotta',
    description: 'Fluffy fried bread served with potato curry',
    price: 35,
    image: '/images/egg veechu parotta.png',
    category: 'meals',
    available: true,
  },
  {
    id: '12',
    name: 'chapathi',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 20,
    image: '/images/chapathi.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '13',
    name: 'idiyappam',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 12,
    image: '/images/idiyappam.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '14',
    name: 'omelette',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 20,
    image: '/images/omelette.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '15',
    name: 'half boi',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 15,
    image: '/images/half boi.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '16',
    name: 'boiled egg.',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 15,
    image: '/images/boiled egg.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '17',
    name: 'egg roast',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 70,
    image: '/images/egg roast.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '18',
    name: 'egg kal dosai',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 40,
    image: '/images/egg kal dosai.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '19',
    name: 'egg kothu',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 110,
    image: '/images/egg kothu.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '20',
    name: 'egg biriyani',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 100,
    image: '/images/egg biriyani.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '21',
    name: 'chicken biriyani.',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 150,
    image: '/images/chicken biriyani.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '22',
    name: 'chicken curry dosai',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 130,
    image: '/images/chicken curry dosai.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '23',
    name: 'chicken chukka',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 120,
    image: '/images/chicken chukka.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '24',
    name: 'chicken masala',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 25,
    image: '/images/chicken masala.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '25',
    name: 'chicken 65',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 90,
    image: '/images/chicken 65.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '26',
    name: 'chilli chicken',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 170,
    image: '/images/chilli chicken.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '27',
    name: 'pepper chicken',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 170,
    image: '/images/pepper chicken.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '28',
    name: 'Butter Chicken',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 180,
    image: '/images/Butter Chicken.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '29',
    name: 'Chettinad Chicken',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 170,
    image: '/images/Chettinad Chicken.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '30',
    name: 'Chicken Kothuc',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 150,
    image: '/images/Chicken Kothuc.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '31',
    name: 'Boneless Chicken',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 130,
    image: '/images/Boneless Chicken.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '32',
    name: 'Boneless Onion Fry',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 150,
    image: '/images/Boneless Onion Fry.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '33',
    name: 'Mutton Biriyani',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 260,
    image: '/images/Mutton Biriyani.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '34',
    name: 'Mutton Kothu',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 240,
    image: '/images/Mutton Kothu.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '35',
    name: 'Mutton Chukka',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 220,
    image: '/images/Mutton Chukka.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '36',
    name: 'Mutton Onion Fry',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 260,
    image: '/images/Mutton Onion Fry.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '37',
    name: 'Mutton Curry Dosai',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 220,
    image: '/images/Mutton Curry Dosai.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '38',
    name: 'Mutton Rice',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 240,
    image: '/images/Mutton Rice.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '40',
    name: 'Mutton Noodles',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 240,
    image: '/images/Mutton Noodles.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '41',
    name: 'Beef Kothu',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 160,
    image: '/images/Beef Kothu.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '42',
    name: 'Beef Chukka',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 120,
    image: '/images/Beef Chukka.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '43',
    name: 'Beef Onion Fry',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 150,
    image: '/images/Beef Onion Fry.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '44',
    name: 'Beef Rice',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 150,
    image: '/images/Beef Rice.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '45',
    name: 'Beef Noodles',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 150,
    image: '/images/Beef Noodles.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '46',
    name: 'Beef Curry Dosai',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 140,
    image: '/images/Beef Curry Dosai.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '47',
    name: 'Beef Biriyani',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 160,
    image: '/images/Beef Biriyani.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '48',
    name: 'Fish Fry',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 100,
    image: '/images/Fish Fry.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '49',
    name: 'Fish Meals',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 200,
    image: '/images/Fish Meals.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '50',
    name: 'Fish Kulambu',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 20,
    image: '/images/Fish Kulambu.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '51',
    name: 'Veg Rice',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 90,
    image: '/images/Veg Rice.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '52',
    name: 'Paneer Rice',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 120,
    image: '/images/Paneer Rice.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '53',
    name: 'Mushroom Rice',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 120,
    image: '/images/Mushroom Rice.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '54',
    name: 'Chicken Rice',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 140,
    image: '/images/Chicken Rice.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '53',
    name: 'Egg Rice',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 110,
    image: '/images/Egg Rice.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '54',
    name: 'Veg Noodles',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 90,
    image: '/images/Veg Noodles.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '55',
    name: 'Chicken Noodles',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 140,
    image: '/images/Chicken Noodles.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '56',
    name: 'Egg Noodles',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 110,
    image: '/images/Egg Noodles.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '57',
    name: 'Grill 1/4',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 120,
    image: '/images/muthu.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '58',
    name: 'Grill off',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 240,
    image: '/images/Grill off.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '59',
    name: 'Full Grill',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 450,
    image: '/images/Full Grill.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '60',
    name: 'Veg Meals',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 120,
    image: '/images/Veg Meals.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '61',
    name: 'Chicken Meals',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 200,
    image: '/images/Chicken Meals.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '62',
    name: 'Mutton Meals',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 260,
    image: '/images/Mutton Meals.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '63',
    name: 'Beef Meals',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 190,
    image: '/images/Beef Meals.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '64',
    name: 'Half Meals',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 70,
    image: '/images/Half Meals.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '65',
    name: 'muhtu vel',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 90,
    image: '/images/chicken 65.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '66',
    name: 'tea',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 12,
    image: '/images/tea.png',
    category: 'snacks',
    available: true,
  },
  {
    id: '67',
    name: 'coffee',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 15,
    image: '/images/coffee.png',
    category: 'snacks',
    available: true,
  },
   {
    id: '68',
    name: 'boost',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 20,
    image: '/images/boost.png',
    category: 'snacks',
    available: true,
  },
   {
    id: '69',
    name: 'Horlicks',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 20,
    image: '/images/Horlicks.png',
    category: 'snacks',
    available: true,
  },
   {
    id: '70',
    name: 'tea',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 12,
    image: '/images/tea.png',
    category: 'snacks',
    available: true,
  },
   {
    id: '71',
    name: 'Lemon Tea',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 30,
    image: '/images/Lemon Tea.png',
    category: 'snacks',
    available: true,
  },
   {
    id: '72',
    name: 'Green Tea',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 15,
    image: '/images/Green Tea.png',
    category: 'snacks',
    available: true,
  },
   {
    id: '73',
    name: 'Fresh Juice',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 80,
    image: '/images/Fresh Juice.png',
    category: 'snacks',
    available: true,
  },
   {
    id: '74',
    name: 'Fresh Juice (Var)',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 60,
    image: '/images/Fresh Juice (Var).png',
    category: 'snacks',
    available: true,
  },
   {
    id: '75',
    name: 'Fresh Juice (Var Small)',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 30,
    image: '/images/Fresh Juice (Var Small).png',
    category: 'snacks',
    available: true,
  },
   {
    id: '76',
    name: 'Badam Milk',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 30,
    image: '/images/Badam Milk.png',
    category: 'snacks',
    available: true,
  },
   {
    id: '77',
    name: 'Water Bottle',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 20,
    image: '/images/Water Bottle.png',
    category: 'snacks',
    available: true,
  },


];
export const dailySpecials: DailySpecial[] = [
  {
    id: 'special-1',
    name: "Today's Special Thali",
    description: 'Extra items with dessert included. Limited quantity available!',
    price: 70,
    originalPrice: 100,
    image: '/images/hero-food.jpg',
    available: true,
    date: new Date().toISOString().split('T')[0],
  },
  {
    id: 'special-2',
    name: 'combo 1',
    description: '2 Idli + 1 Vada + Sambar + Coffee',
    price: 55,
    originalPrice: 75,
    image: '/images/Chicken Meals.png',
    available: true,
    date: new Date().toISOString().split('T')[0],
  },
];

export const categories = [
  { id: 'all', name: 'All Items' },
  { id: 'breakfast', name: 'Breakfast' },
  { id: 'snacks', name: 'Snacks' },
  { id: 'beverages', name: 'Beverages' },
  { id: 'meals', name: 'Meals' },
];

