import { MenuItem, DailySpecial } from './types';

export const menuItems: MenuItem[] = [
  {
    id: '1',
    name: 'Idli, dosa, vada, tea',
    description: 'Soft steamed rice cakes served with sambar and coconut chutney',
    price: 60,
    image: '/images/idli.jpg',
    category: 'breakfast',
    available: true,
  },
  {
    id: '2',
    name: 'Masala Dosa',
    description: 'Crispy fermented crepe filled with spiced potato filling',
    price: 50,
    image: '/images/dosa.jpg',
    category: 'breakfast',
    available: true,
    isSpecial: true,
  },
  {
    id: '3',
    name: 'Plain Dosa',
    description: 'Crispy fermented crepe served with sambar and chutneys',
    price: 40,
    image: '/images/dosa.jpg',
    category: 'breakfast',
    available: true,
  },
  {
    id: '4',
    name: 'Samosa',
    description: 'Crispy pastry filled with spiced potatoes and peas',
    price: 15,
    image: '/images/samosa.jpg',
    category: 'snacks',
    available: true,
  },
  {
    id: '5',
    name: 'Vada Pav',
    description: 'Spiced potato fritter in a soft bun with chutneys',
    price: 20,
    image: '/images/samosa.jpg',
    category: 'snacks',
    available: true,
  },
  {
    id: '6',
    name: 'Masala Chai',
    description: 'Traditional Indian spiced tea with milk',
    price: 20,
    image: '/images/tea.jpg',
    category: 'beverages',
    available: true,
  },
  {
    id: '7',
    name: 'Filter Coffee',
    description: 'Authentic South Indian filter coffee',
    price: 20,
    image: '/images/coffee.jpg',
    category: 'beverages',
    available: true,
  },
  {
    id: '8',
    name: 'Cold Coffee',
    description: 'Refreshing iced coffee with milk and sugar',
    price: 35,
    image: '/images/coffee.jpg',
    category: 'beverages',
    available: true,
  },
  {
    id: '9',
    name: 'vel',
    description: 'Complete meal with dal, sabzi, roti, rice, and salad',
    price: 80,
    image: '/images/hero-food.jpg',
    category: 'meals',
    available: true,
    isSpecial: true,
  },
  {
    id: '10',
    name: 'Chole Bhature',
    description: 'Spiced chickpea curry with fluffy fried bread',
    price: 60,
    image: '/images/hero-food.jpg',
    category: 'meals',
    available: true,
  },
  {
    id: '11',
    name: 'Puri Sabzi',
    description: 'Fluffy fried bread served with potato curry',
    price: 45,
    image: '/images/hero-food.jpg',
    category: 'meals',
    available: true,
  },
  {
    id: '12',
    name: 'Bread Pakora',
    description: 'Crispy gram flour coated bread slices with stuffing',
    price: 25,
    image: '/images/samosa.jpg',
    category: 'snacks',
    available: true,
  },
  
];

export const dailySpecials: DailySpecial[] = [
  {
    id: 'special-1',
    name: "Today's Special Thali",
    description: 'Extra items with dessert included. Limited quantity available!',
    price: 70,
    originalPrice: 100,
    image: '/images/hero-food.jpg',
    available: true,
    date: new Date().toISOString().split('T')[0],
  },
  {
    id: 'special-2',
    name: 'Combo Breakfast',
    description: '2 Idli + 1 Vada + Sambar + Coffee',
    price: 55,
    originalPrice: 75,
    image: '/images/idli.jpg',
    available: true,
    date: new Date().toISOString().split('T')[0],
  },
];

export const categories = [
  { id: 'all', name: 'All Items' },
  { id: 'breakfast', name: 'Breakfast' },
  { id: 'snacks', name: 'Snacks' },
  { id: 'beverages', name: 'Beverages' },
  { id: 'meals', name: 'Meals' },
];
